name: casa_gpt
description: CasaGPT - Aplicação imobiliária. Frontend em Flutter (Feature-Driven Architecture).
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  google_fonts: ^6.2.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
